// <auto-generated />
using System;
using EmployeeManagement.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeManagement.Data.EF.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EmployeeManagement.Data.EF.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "HR"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Admin"
                        },
                        new
                        {
                            ID = 3,
                            Name = "GE"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Data.EF.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOJ")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerID")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("ManagerID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "coimbatore",
                            DOJ = new DateTime(2020, 11, 17, 21, 15, 7, 649, DateTimeKind.Local).AddTicks(9365),
                            DepartmentID = 1,
                            FirstName = "Vineeth",
                            LastName = "Viswanathan"
                        },
                        new
                        {
                            ID = 2,
                            Address = "coimbatore",
                            DOJ = new DateTime(2020, 11, 17, 21, 15, 7, 652, DateTimeKind.Local).AddTicks(7273),
                            DepartmentID = 1,
                            FirstName = "Krishna",
                            LastName = "v",
                            ManagerID = 1
                        },
                        new
                        {
                            ID = 3,
                            Address = "coimbatore",
                            DOJ = new DateTime(2020, 11, 17, 21, 15, 7, 652, DateTimeKind.Local).AddTicks(7703),
                            DepartmentID = 1,
                            FirstName = "Krishna",
                            LastName = "v",
                            ManagerID = 2
                        },
                        new
                        {
                            ID = 4,
                            Address = "coimbatore",
                            DOJ = new DateTime(2020, 11, 17, 21, 15, 7, 652, DateTimeKind.Local).AddTicks(7719),
                            DepartmentID = 2,
                            FirstName = "Krishna",
                            LastName = "v"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Data.EF.Models.Employee", b =>
                {
                    b.HasOne("EmployeeManagement.Data.EF.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeManagement.Data.EF.Models.Employee", "Manager")
                        .WithMany("Reportees")
                        .HasForeignKey("ManagerID");

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("EmployeeManagement.Data.EF.Models.Employee", b =>
                {
                    b.Navigation("Reportees");
                });
#pragma warning restore 612, 618
        }
    }
}
